export const CAMPUSES = [
  { school: "הגבעה",               campus: "איקאה",               instructor: "הדר שלמה" },
  { school: "הגבעה",               campus: "בעלי חיים",           instructor: "חביבה" },
  { school: "הגבעה",               campus: "מוסיקה",              instructor: "טל מלכה" },
  { school: "אשלים",               campus: "אימרסיבי",            instructor: "מור שמואלי" },
  { school: "אשלים",               campus: "יזמות וחדשנות",       instructor: "אשר" },
  { school: "אשלים",               campus: "תקשורת ורדיו",        instructor: "אבי" },
  { school: "בן גוריון",           campus: "מלאכות קדומות",       instructor: "מיטל בוטו" },
  { school: "בן גוריון",           campus: "קניון",               instructor: null },
  { school: "בן גוריון",           campus: "כנסת",                instructor: null },
  { school: "אביר יעקב",           campus: "בנק",                 instructor: null },
  { school: "אביר יעקב",           campus: "או\"ם",               instructor: null },
  { school: "אביר יעקב",           campus: "מיינדפולנס",          instructor: null },
  { school: "רגבים",               campus: "הפיטריותים",          instructor: "קרן מויאל" },
  { school: "רגבים",               campus: "הרפתקה חקלאית",       instructor: "לירז דבי זנגולזס" },
  { school: "גוונים",              campus: "נגרים צעירים",        instructor: "מיכאל" },
  { school: "גוונים",              campus: "תיאטרון",             instructor: "ניל דוד" },
  { school: "גוונים",              campus: "אתלטיקה",             instructor: null },
  { school: "גוונים",              campus: "אומנות",              instructor: null },
  { school: "אולם ספורט חדש",      campus: "היפ הופ",             instructor: "תהילה" },
  { school: "אולם ספורט חדש",      campus: "קרב מגע",             instructor: "יואב" },
  { school: "אולם ספורט חדש",      campus: "אתלטיקה",             instructor: null },
  { school: "אולם ספורט חדש",      campus: "כדורגל",              instructor: null },
  { school: "אולם ספורט חדש",      campus: "כדורשת",              instructor: "קרן בן טוב" },
  { school: "אולם ספורט גולומב",   campus: "כדורסל",              instructor: "מאיר" },
  { school: "אולם ספורט גולומב",   campus: "העצמה אישית",         instructor: null },
  { school: "אולם ספורט גולומב",   campus: "אתגר הנינג'ה",        instructor: null },
  { school: "קולנוע",              campus: "My Story",            instructor: "נדב משעלי" },
  { school: "קולנוע",              campus: "קסם הקולנוע",         instructor: "הדר" },
  { school: "הפקולטה לאנגלית",     campus: "C.L.I.C.K",           instructor: "בית יציב" },
  { school: "הפקולטה לאנגלית",     campus: "F.L.A.S.H",           instructor: "בית יציב" },
];
